# 1. Write a NumPy program to print the NumPy version in your system.

In [2]:
import numpy as np
np.__version__

'1.19.2'

# 2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

Expected Output:

Original List: [12.23, 13.32, 100, 36.32]

One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [7]:
import numpy as np
originalList = [12.23, 13.32, 100, 36.32]
np.array(originalList)

array([ 12.23,  13.32, 100.  ,  36.32])

# 3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.


In [30]:
import numpy as np
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# 4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [21]:
import numpy as np
q4 = np.zeros(10)
q4[6] += 11 # q4[6] = 11
q4

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

# 5. Write a NumPy program to create an array with values ranging from 12 to 38.

Expected Output:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [29]:
import numpy as np
np.arange(12,38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

# 6. Write a NumPy program to reverse an array (first element becomes last). 

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [33]:
import numpy as np
np.arange(12,38)[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

# 7. Write a NumPy program to convert an array to a float type.

Sample output:
Original array
[1, 2, 3, 4]

Array converted to a float type:
[ 1. 2. 3. 4.]

In [41]:
import numpy as np
np.arange(1,5)/1

array([1., 2., 3., 4.])

In [47]:
type(np.arange(1,5)/1)

numpy.ndarray

# 8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [56]:
import numpy as np
q8 = np.ones((5,5))
q8[1:-1,1:-1] = 0
q8

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# 9. Write a NumPy program to add a border (filled with 0's) around an existing array.

Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]

1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
...........
[ 0. 0. 0. 0. 0.]]

In [76]:
import numpy as np
q9 = np.ones((3,3))
q9 = np.append(q9,[1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.]).reshape(5,5)
q9[0:,(0,-1)] = 0
q9[(0,-1),0:] = 0
q9

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

# 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [82]:
import numpy as np
q10 = np.zeros((8,8))
q10[0::2,1::2] = 1
q10[1::2,0::2] = 1
q10

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 11. Write a NumPy program to convert a list and tuple into arrays.

List to array:
[1 2 3 4 5 6 7 8]

Tuple to array:
[[8 4 6]
[1 2 3]]

In [90]:
import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
import numpy as np
np.array([[8, 4, 6], [1, 2, 3]])

array([[8, 4, 6],
       [1, 2, 3]])

# 12. Write a NumPy program to append values to the end of an array.

Expected Output:

Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [16]:
import numpy as np
originalArray = [10,20,30]
np.append(np.array(originalArray), [40, 50, 60, 70, 80, 90])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# 13. Write a NumPy program to create an empty and a full array.

Expected Output:

[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]

[[6 6 6]
[6 6 6]
[6 6 6]]

In [23]:
import numpy as np
np.full((3,3),6.93270651e-310)

array([[6.93270651e-310, 6.93270651e-310, 6.93270651e-310],
       [6.93270651e-310, 6.93270651e-310, 6.93270651e-310],
       [6.93270651e-310, 6.93270651e-310, 6.93270651e-310]])

In [22]:
import numpy as np
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

# 14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array. 

Sample Array [0, 12, 45.21 ,34, 99.91]

Expected Output:
Values in Fahrenheit degrees:
[ 0. 12. 45.21 34. 99.91]

Values in Centigrade degrees:
[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [91]:
import numpy as np
np.array([0, 12, 45.21 ,34, 99.91])  # Values in Fahrenheit degrees.

array([ 0.  , 12.  , 45.21, 34.  , 99.91])

In [94]:
import numpy as np
(np.array([0, 12, 45.21 ,34, 99.91])*5)/9 - 32*5/9  # Values in Centigrade degrees.

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778])