# 1. Write a NumPy program to print the NumPy version in your system.

In [2]:
import numpy as np
np.__version__

'1.19.2'

# 2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

Expected Output:

Original List: [12.23, 13.32, 100, 36.32]

One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [7]:
import numpy as np
originalList = [12.23, 13.32, 100, 36.32]
np.array(originalList)

array([ 12.23,  13.32, 100.  ,  36.32])

# 3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.


# 12. Write a NumPy program to append values to the end of an array.

Expected Output:

Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [16]:
originalArray = [10,20,30]
np.append(np.array(originalArray), [40, 50, 60, 70, 80, 90])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
type(np.append(np.array(originalArray), [40, 50, 60, 70, 80, 90]))

numpy.ndarray

# 13. Write a NumPy program to create an empty and a full array.

Expected Output:

[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]

[[6 6 6]
[6 6 6]
[6 6 6]]

In [23]:
np.full((3,3),6.93270651e-310)

array([[6.93270651e-310, 6.93270651e-310, 6.93270651e-310],
       [6.93270651e-310, 6.93270651e-310, 6.93270651e-310],
       [6.93270651e-310, 6.93270651e-310, 6.93270651e-310]])

In [22]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])